name: Build Debug APK

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get application version name
        run: echo "VERSION_NAME=$(${{github.workspace}}/gradlew -q printVersionName)" >> $GITHUB_ENV

      - name: Bump application version code
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts
          versionName: "${{ env.VERSION_NAME }} (#${{github.run_number}})"

      - name: Write sign info
        if: github.repository == 'DHD2280/BCR-Manager'
        run: |
          if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
            echo storePassword='${{ secrets.KEYSTORE_PASSWORD }}' >> keystore.properties
            echo keyAlias='${{ secrets.KEY_ALIAS }}' >> keystore.properties
            echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> keystore.properties
            echo storeFile='${{ github.workspace }}/key.jks' >> keystore.properties
            echo ${{ secrets.KEYSTORE }} | base64 --decode > ${{ github.workspace }}/key.jks
          fi

      - name: Build with Gradle
        if: github.repository == 'DHD2280/BCR-Manager'
        run: ./gradlew assembleRelease

      - name: Upload a Build Artifact
        if: github.repository == 'DHD2280/BCR-Manager'
        uses: actions/upload-artifact@v4
        with:
          name: "BCR Manager ${{ env.VERSION_NAME }} Dev (#${{github.run_number}})"
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: error
